---
- name: Setup CRIU repository
  apt_repository:
    repo: ppa:criu/ppa
  become: true

- name: Install CRIU
  apt:
    update_cache: true
    name: criu
  become: true

- name: Create /etc/criu
  file:
    path: /etc/criu
    state: directory
  become: true

- name: Create a CRIU configuration file for runC
  copy: src=runc.conf dest=/etc/criu/runc.conf owner=root group=root mode=0755
  become: true
