---
- name: Restart supervisor
  service: name=supervisor state=restarted
  become: true

- name: Restart dummy-server
  supervisorctl:
    name: dummy-server
    state: restarted
    config: /etc/supervisor/conf.d/dummy-server.conf
  become: true