---
- name: Install NFS
  apt:
    name: nfs-kernel-server
  become: true

- name: Configure exports
  template: src=exports.j2 dest=/etc/exports owner=root group=root mode=0644
  notify: restart nfs-server
  become: true
