---
- name: Install HAProxy
  apt:
    update_cache: true
    name: haproxy
  become: true

- name: Create /etc/haproxy/haproxy.cfg
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0755
  become: true
