---
- name: Kill CRIU processes
  command: pkill -f criu
  become: true
  ignore_errors: yes

- name: Stop MySQL container
  command: runc kill -a mysql
  become: true
  ignore_errors: yes

- name: Stop WordPress container
  command: runc kill -a wordpress
  become: true
  ignore_errors: yes

- name: Remove MySQL container
  command: runc delete -f mysql
  become: true
  ignore_errors: yes

- name: Remove WordPress container
  command: runc delete -f wordpress
  become: true
  ignore_errors: yes
