---
- hosts: "{{ target | default('target') }}"
  roles:
  - docker
  - criu
  - networking-tools
  - nfs-target
  - netns

- hosts: "{{ source | default('source') }}"
  roles:
  - docker
  - criu
  # not needed if not generating image
  # - container-tools
  - networking-tools
  - nfs-source
  - netns
