---
- name: Create migrate-target script
  copy: src=migrate-target.py dest=/home/ubuntu/migrate-target.py owner=root group=root mode=0755
  become: true

- name: Start rsync daemon
  command: rsync --daemon
  become: true

- name: Execute migration target script
  shell: "./migrate-target.py {{ hostvars[source].private_address }} >> migrate-target-log"
  args:
    chdir: /home/ubuntu
  become: true
  async: 2629800
  poll: 0
