---
- name: Create migrate-target script
  copy: src=migrate-target.py dest=/home/ubuntu/migrate-target.py owner=root group=root mode=0755
  become: true

- name: Execute migration target script
  command: "./migrate-target.py {{ hostvars[source].private_address }}"
  args:
    chdir: /home/ubuntu
  become: true
  async: 1000
  poll: 0
