---
- name: Create /etc/criu
  file: path=/etc/criu state=directory
  become: true

- name: Create a CRIU configuration file for runC
  copy: src=runc.conf dest=/etc/criu/runc.conf owner=root group=root mode=0755
  become: true

- name: Create migrate-target script
  copy: src=migrate-target.py dest=/home/ubuntu/migrate-target.py owner=root group=root mode=0755
  become: true

- name: Execute migration target script
  command: "./migrate-target.py {{ hostvars[source].private_address }}"
  args:
    chdir: /home/ubuntu
  become: true
  async: 1000
  poll: 0
