---
- name: Create migrate-source script
  copy: src=migrate-source.py dest=/home/ubuntu/migrate-source.py owner=root group=root mode=0755
  become: true

- name: Migrate MySQL and WordPress
  command: "./migrate-source.py mysql,wordpress {{ hostvars[target].private_address }} {{ precopy | default('false') }} {{ postcopy | default('false') }} 8027"
  args:
    chdir: /home/ubuntu
  become: true
  async: 1000
  poll: 0
  register: migrate_task

- name: Check migration result
  async_status: jid="{{ migrate_task.ansible_job_id }}"
  become: true
  register: migrate_result
  until: migrate_result.finished
  retries: 100
