---
- name: Forward port 3306 with socat
  idk: socat tcp-listen:3306,reuseaddr,fork tcp-connect:<mysql ip>:3306 &
  become: true

- name: Forward port 80 with socat
  idk: socat tcp-listen:80,reuseaddr,fork tcp-connect:<wp ip>:80 &
  become: true
