---
- name: Forward port 3306 with socat
  shell: socat tcp-listen:3306,reuseaddr,fork tcp-connect:10.200.1.2:3306
  become: true
  async: 2629800
  poll: 0

- name: Forward port 80 with socat
  shell: socat tcp-listen:80,reuseaddr,fork tcp-connect:10.200.1.5:80
  become: true
  async: 2629800
  poll: 0
