---
- name: Start MySQL container
  # shell: runc run -d mysql & > /dev/null < /dev/null
  shell: runc run -d mysql > ../mysql_logs.txt 2>&1
  args:
    chdir: /home/ubuntu/mysql
  become: true

- name: Start WordPress container
  # shell: runc run -d wordpress & > /dev/null < /dev/null
  shell: runc run -d wordpress > ../wp_logs.txt 2>&1
  args:
    chdir: /home/ubuntu/wordpress
  become: true
