---
- name: Setup Project Atomic repository
  apt_repository:
    repo: ppa:projectatomic/ppa
  become: true

- name: Install skopeo
  apt:
    update_cache: true
    name: skopeo
  become: true

- name: Install umoci
  get_url:
    url: https://github.com/openSUSE/umoci/releases/download/v0.4.4/umoci.amd64
    dest: /usr/local/bin/umoci
    mode: 0755
  become: true
