---
- name: Install python-dev, python-pip, and supervisor
  apt: name={{ item }} update_cache=true state=present
  with_items:
    - python-dev
    - python-pip
    - supervisor
  become: true

- name: Install Flask and Gunicorn
  pip:
    name:
      - Flask
      - gunicorn
      - pymemcache
      - requests
  become: true

- name: Copy server file
  copy: src=dummy-server.py dest=/home/ubuntu/dummy-server.py owner=root group=root mode=0755
  become: true

- name: Copy server supervisord file
  copy: src=dummy-server.conf dest=/etc/supervisor/conf.d/dummy-server.conf owner=root group=root mode=0755
  notify: Restart supervisor
  become: true